### ISSUE TITLE
Installing Apps

### ISSUE THREAD

**Issue by srutto** [brck/CrisisStack#4]
You can currently only install the Ushahidi app. When you try installing Etherpad-Lite, LDLN or Sahana Eden nothing happens, the 'Installing' gif just keeps spinning 
![tinygrab screen shot 10-7-15 10 56 58 am](https://cloud.githubusercontent.com/assets/1751822/10332060/2c24c42c-6ce3-11e5-82e0-0950a3c8fcdc.png)

@Onuonga: 
Action Items:-
Ensure the install process is seamless for the other applications, i.e:
1. Etherpad-Lite
2. LDLN
3. Sahana Eden

Expected Outcome:
When the user/administrator clicks on install, the app should be installed and added to the 'My Applications' section where a user can launch it and use it.

**Comment by Onuonga** [comment]
So you will notice that each application in the MVP is installed differently. 
For the most part , we fetch packages and libraries from the net as we apply some configs. It seems to me that this may not be good and it would actually be easier to have them living on the device and only activated when install is selected. This would give a smoother user experience. 
This has also been inspired by bad net connections causing the front end not to behave as well as I had expected. 

To this regard, I am switching the way I handle this logic to let supervisor activate the service when required. I also did not see this benefit coming in but it handles service restarts incase it goes down. This is because Etherpad-lite is initiated by a script
